=== nata154/TeamWork/src/test/resources/JsonSchemas/newsFeedJsonSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "required": [
    "key",
    "name",
    "lang",
    "img"
  ],
  "items": {
    "properties": {
      "key": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "lang": {
        "type": "string"
      },
      "img": {
        "type": "string"
      }
    },
    "additionalProperties": false
  }
}

=== nata154/TeamWork/src/test/resources/JSON Objects/newsFeed.json
[
  {
    "key": "cryptocompare",
    "name": "CryptoCompare",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptocompare.png"
  },
  {
    "key": "cryptoglobe",
    "name": "CryptoGlobe",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptoglobe.png"
  },
  {
    "key": "cryptonewsreview",
    "name": "CryptoNewsReview",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptonewsreview.png"
  },
  {
    "key": "coindesk",
    "name": "CoinDesk",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/coindesk.png"
  },
  {
    "key": "bitcoinmagazine",
    "name": "Bitcoin Magazine",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/bitcoinmagazine.png"
  },
  {
    "key": "yahoofinance",
    "name": "Yahoo Finance Bitcoin",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/yahoofinance.png"
  },
  {
    "key": "ccn",
    "name": "CCN",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/ccn.png"
  },
  {
    "key": "financemagnates",
    "name": "Finance Magnates",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/financemagnates.png"
  },
  {
    "key": "espaciobit",
    "name": "EspacioBit",
    "lang": "ES",
    "img": "https://images.cryptocompare.com/news/default/espaciobit.png"
  },
  {
    "key": "99bitcoins",
    "name": "99bitcoins",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/99bitcoins.png"
  },
  {
    "key": "bitcoinist",
    "name": "Bitcoinist",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/bitcoinist.png"
  },
  {
    "key": "bitcoin.com",
    "name": "Bitcoin.com",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/bitcoincom.png"
  },
  {
    "key": "ethnews.com",
    "name": "ETHNews.com",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/ethnews.png"
  },
  {
    "key": "cointelegraph",
    "name": "CoinTelegraph",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cointelegraph.png"
  },
  {
    "key": "cointelegraph_es",
    "name": "CoinTelegraph",
    "lang": "ES",
    "img": "https://images.cryptocompare.com/news/default/cointelegraph.png"
  },
  {
    "key": "cryptovest",
    "name": "CryptoVest",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptovest.png"
  },
  {
    "key": "cryptoinsider",
    "name": "CryptoInsider",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptoinsider.png"
  },
  {
    "key": "livebitcoinnews",
    "name": "Live Bitcoin News",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/livebitcoinnews.png"
  },
  {
    "key": "newsbtc",
    "name": "NewsBTC",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/newsbtc.png"
  },
  {
    "key": "coinspeaker",
    "name": "CoinSpeaker",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/coinspeaker.png"
  },
  {
    "key": "coinjoker",
    "name": "CoinJoker",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/coinjoker.png"
  },
  {
    "key": "trustnodes",
    "name": "TrustNodes",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/trustnodes.png"
  },
  {
    "key": "themerkle",
    "name": "NullTx",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/nulltx.png"
  },
  {
    "key": "cryptocoremedia",
    "name": "Crypto CoreMedia",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/coremedia.png"
  },
  {
    "key": "cryptopotato",
    "name": "Crypto Potato",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptopotato.png"
  },
  {
    "key": "coinnounce",
    "name": "Coinnounce",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/coinnounce.png"
  },
  {
    "key": "blokt",
    "name": "Blokt",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/blokt.png"
  },
  {
    "key": "cointelligence",
    "name": "Cointelligence",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cointelligence.png"
  },
  {
    "key": "ethereumworldnews",
    "name": "Ethereum World News",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/ethereumworldnews.png"
  },
  {
    "key": "ambcrypto",
    "name": "AMB Crypto",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/ambcrypto.png"
  },
  {
    "key": "ambcrypto_es",
    "name": "AMB Crypto",
    "lang": "ES",
    "img": "https://images.cryptocompare.com/news/default/ambcrypto.png"
  },
  {
    "key": "cryptobriefing",
    "name": "Crypto Briefing",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptobriefing.png"
  },
  {
    "key": "cryptoslate",
    "name": "CryptoSlate",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptoslate.png"
  },
  {
    "key": "coingape",
    "name": "CoinGape",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/coingape.png"
  },
  {
    "key": "dailyhodl",
    "name": "The Daily Hodl",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/dailyhodl.png"
  },
  {
    "key": "bitcoinerx",
    "name": "Bitcoinerx",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/bitcoinerx.png"
  },
  {
    "key": "chaindd",
    "name": "Chaindd",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/chaindd.png"
  },
  {
    "key": "cryptonewsz",
    "name": "CryptoNewsZ",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptonewsz.png"
  },
  {
    "key": "criptonoticias",
    "name": "CriptoNoticias",
    "lang": "ES",
    "img": "https://images.cryptocompare.com/news/default/cryptonoticias.png"
  },
  {
    "key": "diariobitcoin",
    "name": "DiarioBitcoin",
    "lang": "ES",
    "img": "https://images.cryptocompare.com/news/default/diariobitcoin.png"
  },
  {
    "key": "cryptopolitan",
    "name": "Cryptopolitan",
    "lang": "EN",
    "img": "https://images.cryptocompare.com/news/default/cryptopolitan.png"
  }
]
